name: url-shortener
services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - mongo-data:/data/db

  api-backend:
    build:
      context: ./UrlShortenerApi
      dockerfile: Dockerfile
    container_name: api-backend
    ports:
      - "5009:5009"
    networks:
      - app-net
    depends_on:
      - mongo

  front-image:
    build:
      context: ./urlshortenerfrontend
      dockerfile: Dockerfile
    container_name: api-frontend
    ports:
      - "3000:80"
    networks:
      - app-net
    depends_on:
      - api-backend

networks:
  app-net:
    driver: bridge

volumes:
  mongo-data: